name: 'Terraform CI/CD'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'

permissions: write-all

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        skip_check: CKV_AWS_79,CKV_AWS_126
        output_format: cli,sarif
        output_file: results.sarif
        soft_fail: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: results.sarif

    - name: Ensure S3 bucket exists
      run: |
        aws s3api head-bucket --bucket groupthreesix-terraform-state 2>/dev/null || \
        aws s3api create-bucket --bucket groupthreesix-terraform-state --region us-east-1

    - name: Enable S3 bucket versioning
      run: |
        aws s3api put-bucket-versioning \
          --bucket groupthreesix-terraform-state \
          --versioning-configuration Status=Enabled

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -var="user_ip=${{ secrets.USER_IP }}" -no-color
      continue-on-error: true

    - name: Terraform Apply
      run: terraform apply -var="user_ip=${{ secrets.USER_IP }}" -auto-approve 
